@echo off
echo NextSefer başlatılıyor...

echo 1. Django sunucusu başlatılıyor...
start "Django Server" cmd /k "start_django_server.bat"

echo 2. 5 saniye bekleniyor...
ping 127.0.0.1 -n 6 > nul

echo 3. Electron uygulaması başlatılıyor...
npm start 