# Generated by Django 5.2.1 on 2025-05-31 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AracBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20, unique=True)),
                ('arac_tipi', models.CharField(max_length=50)),
                ('kullanim_sekli', models.CharField(max_length=50)),
                ('arac_durumu', models.CharField(max_length=50)),
                ('marka', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('model_yili', models.PositiveIntegerField(blank=True, null=True)),
                ('yakit_tipi', models.CharField(max_length=50)),
                ('motor_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sasi_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('kilometre', models.PositiveIntegerField(default=0)),
                ('lastik_olculeri', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
            },
        ),
        migrations.CreateModel(
            name='Firmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirmaTipi', models.CharField(max_length=50)),
                ('FirmaAdi', models.CharField(max_length=255)),
                ('YetkiliKisi', models.CharField(blank=True, max_length=150, null=True)),
                ('AktifMi', models.BooleanField(default=True)),
                ('Telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('Eposta', models.EmailField(blank=True, max_length=254, null=True)),
                ('WebSitesi', models.URLField(blank=True, null=True)),
                ('Adres', models.TextField(blank=True, null=True)),
                ('VergiNumarasi', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('VergiDairesi', models.CharField(blank=True, max_length=100, null=True)),
                ('ParaBirimi', models.CharField(max_length=10)),
                ('Notlar', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.CreateModel(
            name='Kasalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasa_adi', models.CharField(max_length=100)),
                ('kasa_tipi', models.CharField(max_length=50)),
                ('para_birimi', models.CharField(max_length=10)),
                ('baslangic_bakiyesi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aciklama', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kasa',
                'verbose_name_plural': 'Kasalar',
            },
        ),
        migrations.CreateModel(
            name='Personeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PerAd', models.CharField(max_length=100)),
                ('PerSoyad', models.CharField(max_length=100)),
                ('VatandaslikNo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('DogumTarihi', models.DateField(blank=True, null=True)),
                ('Telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('Eposta', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Adres', models.TextField(blank=True, null=True)),
                ('Departman', models.CharField(max_length=100)),
                ('Pozisyon', models.CharField(max_length=100)),
                ('Maas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IseBaslangicTarihi', models.DateField(blank=True, null=True)),
                ('Durum', models.CharField(max_length=50)),
                ('Aciklama', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
            },
        ),
        migrations.CreateModel(
            name='Sehirler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir_adi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
            },
        ),
        migrations.CreateModel(
            name='Ulkeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulke_adi', models.CharField(max_length=100, unique=True)),
                ('ulke_kodu', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ülke',
                'verbose_name_plural': 'Ülkeler',
            },
        ),
        migrations.CreateModel(
            name='AracBakim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakim_turu', models.CharField(max_length=100)),
                ('bakim_tarihi', models.DateField()),
                ('yapilan_islemler', models.TextField()),
                ('maliyet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bir_sonraki_bakim_km', models.PositiveIntegerField(blank=True, null=True)),
                ('bir_sonraki_bakim_tarihi', models.DateField(blank=True, null=True)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakimlar', to='sefer_app.aracbilgileri')),
            ],
            options={
                'verbose_name': 'Araç Bakım',
                'verbose_name_plural': 'Araç Bakımları',
            },
        ),
        migrations.CreateModel(
            name='AracUyari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uyari_turu', models.CharField(max_length=100)),
                ('uyari_mesaji', models.TextField()),
                ('olusturma_tarihi', models.DateField(auto_now_add=True)),
                ('son_tarih', models.DateField(blank=True, null=True)),
                ('durum', models.CharField(default='Aktif', max_length=50)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyarilar', to='sefer_app.aracbilgileri')),
            ],
            options={
                'verbose_name': 'Araç Uyarı',
                'verbose_name_plural': 'Araç Uyarıları',
            },
        ),
        migrations.AddField(
            model_name='aracbilgileri',
            name='atanmis_sofor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sefer_app.personeller'),
        ),
        migrations.CreateModel(
            name='Seferler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sefer_kodu', models.CharField(max_length=50, unique=True)),
                ('yuk_cinsi', models.CharField(max_length=100)),
                ('durum', models.CharField(max_length=50)),
                ('cikis_tarihi', models.DateTimeField()),
                ('tahmini_varis_tarihi', models.DateTimeField()),
                ('baslangic_km', models.PositiveIntegerField(blank=True, null=True)),
                ('bitis_km', models.PositiveIntegerField(blank=True, null=True)),
                ('guzergah', models.TextField(blank=True)),
                ('mesafe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ucret', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefer_app.aracbilgileri')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefer_app.firmalar')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefer_app.personeller')),
                ('baslangic_sehri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baslangic_seferleri', to='sefer_app.sehirler')),
                ('bitis_sehri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitis_seferleri', to='sefer_app.sehirler')),
                ('baslangic_ulkesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baslangic_seferleri', to='sefer_app.ulkeler')),
                ('bitis_ulkesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitis_seferleri', to='sefer_app.ulkeler')),
            ],
            options={
                'verbose_name': 'Sefer',
                'verbose_name_plural': 'Seferler',
            },
        ),
        migrations.CreateModel(
            name='Faturalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FaturaTipi', models.CharField(max_length=50)),
                ('FaturaNo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('FaturaTarihi', models.DateField()),
                ('VadeTarihi', models.DateField(blank=True, null=True)),
                ('AraToplam', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ParaBirimi', models.CharField(max_length=10)),
                ('KurEUR', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ToplamEUR', models.DecimalField(decimal_places=2, max_digits=12)),
                ('KDVOrani', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ToplamTutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OdenenTutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OdemeDurumu', models.CharField(max_length=50)),
                ('Aciklama', models.TextField(blank=True, null=True)),
                ('Firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sefer_app.firmalar')),
                ('Sefer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sefer_app.seferler')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
            },
        ),
        migrations.CreateModel(
            name='SeferMasraf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarih', models.DateField()),
                ('Tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ParaBirimi', models.CharField(max_length=10)),
                ('KurEUR', models.DecimalField(decimal_places=4, max_digits=10)),
                ('TutarEUR', models.DecimalField(decimal_places=2, max_digits=12)),
                ('OdemeYontemi', models.CharField(blank=True, max_length=50, null=True)),
                ('BelgeNo', models.CharField(blank=True, max_length=50, null=True)),
                ('Aciklama', models.TextField(blank=True, null=True)),
                ('Kasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sefer_app.kasalar')),
                ('Sefer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sefer_app.seferler')),
            ],
            options={
                'verbose_name': 'Sefer Masraf',
                'verbose_name_plural': 'Sefer Masrafları',
            },
        ),
        migrations.AddField(
            model_name='sehirler',
            name='ulke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sehirler', to='sefer_app.ulkeler'),
        ),
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UrunHizmetAdi', models.CharField(max_length=255)),
                ('Miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Birim', models.CharField(blank=True, max_length=50, null=True)),
                ('BirimFiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('KDVOrani', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Indirim', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Toplam', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Urunler', to='sefer_app.faturalar')),
            ],
            options={
                'verbose_name': 'Ürün/Hizmet',
                'verbose_name_plural': 'Ürünler/Hizmetler',
            },
        ),
    ]
