# Generated by Django 5.2.1 on 2025-06-01 01:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urunler',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.RenameField(
            model_name='urunler',
            old_name='UrunHizmetAdi',
            new_name='Urun',
        ),
        migrations.RemoveField(
            model_name='faturalar',
            name='KurEUR',
        ),
        migrations.RemoveField(
            model_name='faturalar',
            name='ToplamEUR',
        ),
        migrations.RemoveField(
            model_name='urunler',
            name='Indirim',
        ),
        migrations.RemoveField(
            model_name='urunler',
            name='KDVOrani',
        ),
        migrations.RemoveField(
            model_name='urunler',
            name='Toplam',
        ),
        migrations.AddField(
            model_name='faturalar',
            name='GuncellenmeTarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faturalar',
            name='Notlar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturalar',
            name='OlusturmaTarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='urunler',
            name='Aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urunler',
            name='KDV',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='urunler',
            name='ToplamTutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='AraToplam',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='FaturaNo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='FaturaTipi',
            field=models.CharField(choices=[('Alış', 'Alış'), ('Satış', 'Satış'), ('Nakliye', 'Nakliye')], default='Satış', max_length=20),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='Firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sefer_app.firmalar'),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='KDVOrani',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='OdemeDurumu',
            field=models.CharField(choices=[('Ödenmedi', 'Ödenmedi'), ('Kısmi Ödeme', 'Kısmi Ödeme'), ('Ödendi', 'Ödendi')], default='Ödenmedi', max_length=20),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='OdenenTutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='ParaBirimi',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='Sefer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturalar', to='sefer_app.seferler'),
        ),
        migrations.AlterField(
            model_name='faturalar',
            name='ToplamTutar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='Birim',
            field=models.CharField(default='Adet', max_length=50),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='BirimFiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='Fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='sefer_app.faturalar'),
        ),
        migrations.AlterField(
            model_name='urunler',
            name='Miktar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='FaturaOdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OdemeTarihi', models.DateField()),
                ('Tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OdemeTipi', models.CharField(choices=[('Nakit', 'Nakit'), ('Banka Transferi', 'Banka Transferi'), ('Kredi Kartı', 'Kredi Kartı'), ('Çek', 'Çek'), ('Senet', 'Senet')], default='Nakit', max_length=20)),
                ('Aciklama', models.TextField(blank=True, null=True)),
                ('OlusturmaTarihi', models.DateTimeField(auto_now_add=True)),
                ('Fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='sefer_app.faturalar')),
                ('Kasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatura_odemeleri', to='sefer_app.kasalar')),
            ],
            options={
                'verbose_name': 'Fatura Ödeme',
                'verbose_name_plural': 'Fatura Ödemeleri',
            },
        ),
        migrations.CreateModel(
            name='GenelKasaHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('Gelir', 'Gelir'), ('Gider', 'Gider')], max_length=10)),
                ('kategori', models.CharField(max_length=100)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateField()),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('belge_no', models.CharField(blank=True, max_length=50, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genel_hareketler', to='sefer_app.kasalar')),
            ],
            options={
                'verbose_name': 'Genel Kasa Hareketi',
                'verbose_name_plural': 'Genel Kasa Hareketleri',
            },
        ),
        migrations.CreateModel(
            name='KasaTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('hedef_kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinan_transferler', to='sefer_app.kasalar')),
                ('kaynak_kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_transferler', to='sefer_app.kasalar')),
            ],
            options={
                'verbose_name': 'Kasa Transferi',
                'verbose_name_plural': 'Kasa Transferleri',
            },
        ),
    ]
