# Generated by Django 5.2.1 on 2025-06-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0002_alter_urunler_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sefermasraf',
            name='MasrafTipi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
