# Generated by Django 5.2.1 on 2025-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0003_sefermasraf_masraftipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaBirimleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=3, unique=True)),
                ('ad', models.CharField(max_length=50)),
                ('sembol', models.CharField(blank=True, max_length=5, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Para Birimi',
                'verbose_name_plural': 'Para Birimleri',
            },
        ),
    ]
