# Generated by Django 5.2.1 on 2025-06-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0004_parabirimleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmalar',
            name='Sehir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmalar', to='sefer_app.sehirler'),
        ),
        migrations.AddField(
            model_name='firmalar',
            name='Ulke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmalar', to='sefer_app.ulkeler'),
        ),
    ]
