# Generated by Django 5.2.1 on 2025-06-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0005_firmalar_sehir_firmalar_ulke'),
    ]

    operations = [
        migrations.AddField(
            model_name='aracbakim',
            name='kasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakim_harcamalari', to='sefer_app.kasalar'),
        ),
        migrations.AddField(
            model_name='aracbakim',
            name='kur',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aracbakim',
            name='maliyet_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aracbakim',
            name='para_birimi',
            field=models.CharField(default='TRY', max_length=10),
        ),
    ]
