# Generated by Django 5.2.1 on 2025-06-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0006_aracbakim_kasa_aracbakim_kur_aracbakim_maliyet_eur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YeniAracBakim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakim_turu', models.CharField(max_length=100)),
                ('bakim_tarihi', models.DateField()),
                ('kilometre', models.PositiveIntegerField(blank=True, null=True)),
                ('yapilan_islemler', models.TextField(blank=True)),
                ('maliyet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('para_birimi', models.CharField(default='TRY', max_length=10)),
                ('kur', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('maliyet_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bir_sonraki_bakim_km', models.PositiveIntegerField(blank=True, null=True)),
                ('bir_sonraki_bakim_tarihi', models.DateField(blank=True, null=True)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeni_bakimlar', to='sefer_app.aracbilgileri')),
                ('kasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yeni_bakim_harcamalari', to='sefer_app.kasalar')),
                ('kasa_hareketi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bakim_kaydi', to='sefer_app.genelkasahareketi')),
            ],
            options={
                'verbose_name': 'Yeni Araç Bakım',
                'verbose_name_plural': 'Yeni Araç Bakımları',
            },
        ),
    ]
