# Generated by Django 5.2.1 on 2025-06-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0007_yeniaracbakim'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeniaracbakim',
            name='belge_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
