# Generated by Django 5.2.1 on 2025-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0008_yeniaracbakim_belge_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='aracuyari',
            name='bildirim_turu',
            field=models.CharField(blank=True, default='Sistem', help_text='Uyarı bildiriminin nasıl yapılacağını belirtir (SMS, E-posta, Sistem)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aracuyari',
            name='hatirlatici_gun',
            field=models.PositiveIntegerField(default=7, help_text='Son tarihten kaç gün önce hatırlatma yapılacağı'),
        ),
        migrations.AddField(
            model_name='aracuyari',
            name='kategori',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aracuyari',
            name='notlar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aracuyari',
            name='oncelik',
            field=models.CharField(choices=[('Düşük', 'Düşük'), ('Normal', 'Normal'), ('Yüksek', 'Yüksek'), ('Acil', 'Acil')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='aracuyari',
            name='tamamlanma_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aracuyari',
            name='durum',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tamamlandı', 'Tamamlandı'), ('İptal', 'İptal')], default='Aktif', max_length=50),
        ),
        migrations.AlterField(
            model_name='aracuyari',
            name='uyari_turu',
            field=models.CharField(choices=[('Bakım', 'Bakım'), ('Sigorta', 'Sigorta'), ('Muayene', 'Muayene'), ('Vergi', 'Vergi'), ('Lastik Değişimi', 'Lastik Değişimi'), ('Yağ Değişimi', 'Yağ Değişimi'), ('Belge Yenileme', 'Belge Yenileme'), ('Diğer', 'Diğer')], default='Bakım', max_length=100),
        ),
    ]
