# Generated by Django 5.2.1 on 2025-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0010_alter_aracuyari_durum_alter_aracuyari_oncelik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasatransfer',
            name='kur',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
