# Generated by Django 5.2.1 on 2025-06-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0011_kasatransfer_kur'),
    ]

    operations = [
        migrations.AddField(
            model_name='seferler',
            name='notlar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seferler',
            name='toplam_kilometre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seferler',
            name='varis_kilometre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seferler',
            name='varis_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
