# Generated by Django 5.2.1 on 2025-06-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0012_seferler_notlar_seferler_toplam_kilometre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasalar',
            name='kasa_tipi',
            field=models.CharField(choices=[('Nakit', 'Nakit'), ('Banka', 'Banka'), ('Kredi Kartı', 'Kredi Kartı'), ('Sanal POS', 'Sanal POS'), ('Diğer', 'Diğer')], default='Nakit', max_length=50),
        ),
    ]
