# Generated by Django 5.2.1 on 2025-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aracbilgileri',
            name='ilk_kilometre',
            field=models.PositiveIntegerField(default=0, help_text='Araç satın alındığındaki kilometre değeri'),
        ),
        migrations.AlterField(
            model_name='aracbilgileri',
            name='kilometre',
            field=models.PositiveIntegerField(default=0, help_text='Aracın güncel kilometre değeri'),
        ),
    ]
