# Generated by Django 5.2.1 on 2025-06-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0015_aracbilgileri_ilk_kilometre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aracbilgileri',
            name='kilometre',
        ),
    ]
