# Generated by Django 5.2.1 on 2025-06-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0018_genelkasahareketi_gider_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelodeme',
            name='kasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel_odemeleri', to='sefer_app.kasalar'),
        ),
    ]
