# Generated by Django 5.2.1 on 2025-06-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefer_app', '0019_personelodeme_kasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvan', models.CharField(max_length=255, verbose_name='Firma Ünvanı')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('telefon', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('eposta', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('vergi_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi No')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Dairesi')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web Sitesi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firma Bilgisi',
                'verbose_name_plural': 'Firma Bilgileri',
            },
        ),
    ]
